config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :contractors
  resources :preferences
  resources :properties
  resources :timings
  resources :projects
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contractor.rb
class Contractor < ApplicationRecord
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  before_action :set_contractor, only: [:show, :edit, :update, :destroy]

  # GET /contractors
  # GET /contractors.json
  def index
    @contractors = Contractor.all
  end

  # GET /contractors/1
  # GET /contractors/1.json
  def show
  end

  # GET /contractors/new
  def new
    @contractor = Contractor.new
  end

  # GET /contractors/1/edit
  def edit
  end

  # POST /contractors
  # POST /contractors.json
  def create
    @contractor = Contractor.new(contractor_params)

    respond_to do |format|
      if @contractor.save
        format.html { redirect_to @contractor, notice: 'Contractor was successfully created.' }
        format.json { render :show, status: :created, location: @contractor }
      else
        format.html { render :new }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contractors/1
  # PATCH/PUT /contractors/1.json
  def update
    respond_to do |format|
      if @contractor.update(contractor_params)
        format.html { redirect_to @contractor, notice: 'Contractor was successfully updated.' }
        format.json { render :show, status: :ok, location: @contractor }
      else
        format.html { render :edit }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contractors/1
  # DELETE /contractors/1.json
  def destroy
    @contractor.destroy
    respond_to do |format|
      format.html { redirect_to contractors_url, notice: 'Contractor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contractor
      @contractor = Contractor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contractor_params
      params.require(:contractor).permit(:name)
    end
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/views/contractors/_form.html.erb
<%= form_for(contractor) do |f| %>
  <% if contractor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contractor.errors.count, "error") %> prohibited this contractor from being saved:</h2>

      <ul>
      <% contractor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contractors/edit.html.erb
<h1>Editing Contractor</h1>

<%= render 'form', contractor: @contractor %>

<%= link_to 'Show', @contractor %> |
<%= link_to 'Back', contractors_path %>

app/views/contractors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contractors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contractors.each do |contractor| %>
      <tr>
        <td><%= contractor.name %></td>
        <td><%= link_to 'Show', contractor %></td>
        <td><%= link_to 'Edit', edit_contractor_path(contractor) %></td>
        <td><%= link_to 'Destroy', contractor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contractor', new_contractor_path %>

app/views/contractors/new.html.erb
<h1>New Contractor</h1>

<%= render 'form', contractor: @contractor %>

<%= link_to 'Back', contractors_path %>

app/views/contractors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contractor.name %>
</p>

<%= link_to 'Edit', edit_contractor_path(@contractor) %> |
<%= link_to 'Back', contractors_path %>