config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :contractors
  resources :preferences
  resources :properties
  resources :timings
  resources :projects
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/preference.rb
class Preference < ApplicationRecord
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :set_preference, only: [:show, :edit, :update, :destroy]

  # GET /preferences
  # GET /preferences.json
  def index
    @preferences = Preference.all
  end

  # GET /preferences/1
  # GET /preferences/1.json
  def show
  end

  # GET /preferences/new
  def new
    @preference = Preference.new
  end

  # GET /preferences/1/edit
  def edit
  end

  # POST /preferences
  # POST /preferences.json
  def create
    @preference = Preference.new(preference_params)

    respond_to do |format|
      if @preference.save
        format.html { redirect_to @preference, notice: 'Preference was successfully created.' }
        format.json { render :show, status: :created, location: @preference }
      else
        format.html { render :new }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preferences/1
  # PATCH/PUT /preferences/1.json
  def update
    respond_to do |format|
      if @preference.update(preference_params)
        format.html { redirect_to @preference, notice: 'Preference was successfully updated.' }
        format.json { render :show, status: :ok, location: @preference }
      else
        format.html { render :edit }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferences/1
  # DELETE /preferences/1.json
  def destroy
    @preference.destroy
    respond_to do |format|
      format.html { redirect_to preferences_url, notice: 'Preference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preference
      @preference = Preference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preference_params
      params.require(:preference).permit(:preference)
    end
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/preferences/_form.html.erb
<%= form_for(preference) do |f| %>
  <% if preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(preference.errors.count, "error") %> prohibited this preference from being saved:</h2>

      <ul>
      <% preference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :preference %>
    <%= f.text_field :preference %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preferences/edit.html.erb
<h1>Editing Preference</h1>

<%= render 'form', preference: @preference %>

<%= link_to 'Show', @preference %> |
<%= link_to 'Back', preferences_path %>

app/views/preferences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Preferences</h1>

<table>
  <thead>
    <tr>
      <th>Preference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @preferences.each do |preference| %>
      <tr>
        <td><%= preference.preference %></td>
        <td><%= link_to 'Show', preference %></td>
        <td><%= link_to 'Edit', edit_preference_path(preference) %></td>
        <td><%= link_to 'Destroy', preference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preference', new_preference_path %>

app/views/preferences/new.html.erb
<h1>New Preference</h1>

<%= render 'form', preference: @preference %>

<%= link_to 'Back', preferences_path %>

app/views/preferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Preference:</strong>
  <%= @preference.preference %>
</p>

<%= link_to 'Edit', edit_preference_path(@preference) %> |
<%= link_to 'Back', preferences_path %>